name: Branch Name Check

on:
  push:
    branches:
      - '**'  # Trigger on any branch push

jobs:
  check-branch-name:
    runs-on: ubuntu-latest

    steps:
    - name: Check Branch Name
      run: |
        BRANCH_NAME="${GITHUB_REF#refs/heads/}"
        if [[ ! "$BRANCH_NAME" =~ ^(feature|bugfix|hotfix)/.+$ ]]; then
          echo "Branch name '$BRANCH_NAME' does not match the required pattern."
          exit 1
        fi
